### PR TITLE
Use TableTraits.isiterabletable in rows and columns

### LINKED ISSUE #33: DataFrame(load("file.xlsx", "sheetname")) not working
After a recent update in `DataFrames` v0.18, the line `DataFrame(load("file.xlsx", "sheetname"))` no longer works to read an Excel file into a DataFrame. I get the following error:

> ArgumentError: no default `Tables.columns` implementation for type: ExcelFiles.ExcelFile
> 
> Stacktrace:
>  [1] #DataFrame#365(::Bool, ::Type, ::ExcelFiles.ExcelFile) at .julia/packages/Tables/qlc3J/src/fallbacks.jl:156
>  [2] DataFrame(::ExcelFiles.ExcelFile) at .julia/packages/DataFrames/dXFYy/src/other/tables.jl:20
> 

It seems `ExcelFiles` needs to update to use the `Tables` API.

### PR DESCRIPTION
**Pull request by nalimilan**
Otherwise we misdetect some table types which do not define `Base.iterable`, like `ExcelFile`.
Add a new test for this pattern.

Fixes https://github.com/queryverse/ExcelFiles.jl/issues/33, which appeared after https://github.com/JuliaData/Tables.jl/pull/84.

CI fails due to version incompatibilities, not sure why (EDIT: that's https://github.com/JuliaData/Tables.jl/issues/88).

### CODE REVIEW

**Comment by quinnj** [comment]
Thanks!

File: src/fallbacks.jl [hunk 1]
```diff
@@ -58,7 +58,7 @@ function rows(x::T) where {T}
     if columnaccess(T)
         cols = columns(x)
         return RowIterator(cols, rowcount(cols))
-    elseif Base.isiterable(T)
+    elseif TableTraits.isiterabletable(x) === true || Base.isiterable(T)
```
Comment (davidanthoff) [inline src/fallbacks.jl:61]: I think we could further simplify this: `TableTraits.isiterabletable(x)` will return `true` if `Base.isiterable(T)` is `true`, so we don't need that second test. Also, I think we also want to take this branch if `TableTraits.isiterabletable(x)===missing`, right? So I think the test should probably read `elseif TableTraits.isiterabletable(x) !== false`.

But having said this, this PR is clearly fixing a bug already, so thanks for opening it!

Comment (nalimilan) [reply src/fallbacks.jl:61]: You're clearly the expert here, so feel free to open a PR to improve this.

Comment (davidanthoff) [reply src/fallbacks.jl:61]: Will do once I'm done with my current travel stint. @quinnj could you tag a bug fix release that includes this PR soon? Tables v0.2.0 broke the entire file IO story in Queryverse, and this PR fixes that.
