### PR TITLE
Fix #25 by defining a scalarconvert function with the needed definitions

### LINKED ISSUE #25: iterator error with Query and DataValues
Iterating array of NamedTuples with DataValue elements throws an error if Tables is loaded. The example below works until DataFrames v0.14.0 is loaded (which has dependency on Tables). Error is caused by trying to perform something like `DataValue{String}(DataValue("abc"))`.

```julia
julia> using DataValues, Query

julia> x = [(a = DataValue("hello"), b = DataValue(1)), (a = DataValue("world"), b = DataValue(2))]
2-element Array{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},1}:
 (a = DataValue{String}("hello"), b = DataValue{Int64}(1))
 (a = DataValue{String}("world"), b = DataValue{Int64}(2))

julia> y = x |> @map({a = get(_.a), b = get(_.b)})
2x2 query result
a     │ b
──────┼──
hello │ 1
world │ 2

julia> using DataFrames

julia> y = x |> @map({a = get(_.a), b = get(_.b)})
Error showing value of type QueryOperators.EnumerableMap{NamedTuple{(:a, :b),Tuple{String,Int64}},QueryOperators.EnumerableIterable{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},Tables.DataValueRowIterator{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},Array{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},1}}},getfield(Main, Symbol("##8#10"))}:
ERROR: MethodError: Cannot `convert` an object of type DataValue{String} to an object of type String
Closest candidates are:
  convert(::Type{String}, ::Symbol) at deprecated.jl:53
  convert(::Type{String}, ::Array{UInt8,1}) at deprecated.jl:53
  convert(::Type{String}, ::AbstractArray{Char,1}) at deprecated.jl:53
  ...
Stacktrace:
 [1] DataValue{String}(::DataValue{String}) at C:\Users\ky642d\.julia\packages\DataValues\SNSrX\src\scalar\core.jl:18
 [2] _collect(::UnitRange{Int64}, ::Base.Iterators.Take{QueryOperators.EnumerableMap{NamedTuple{(:a, :b),Tuple{String,Int64}},QueryOperators.EnumerableIterable{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},Tables.DataValueRowIterator{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},Array{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},1}}},getfield(Main, Symbol("##8#10"))}}, ::Base.HasEltype, ::Base.HasLength) at C:\Users\ky642d\.julia\packages\Tables\FOeDg\src\datavalues.jl:35
 [3] collect at .\array.jl:557 [inlined]
 [4] |> at .\operators.jl:813 [inlined]
 [5] #printtable#1(::Bool, ::Function, ::IOContext{REPL.Terminals.TTYTerminal}, ::QueryOperators.EnumerableMap{NamedTuple{(:a, :b),Tuple{String,Int64}},QueryOperators.EnumerableIterable{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},Tables.DataValueRowIterator{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},Array{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},1}}},getfield(Main, Symbol("##8#10"))}, ::String) at C:\Users\ky642d\.julia\packages\TableShowUtils\miy4j\src\TableShowUtils.jl:14
 [6] printtable at C:\Users\ky642d\.julia\packages\TableShowUtils\miy4j\src\TableShowUtils.jl:7 [inlined]
 [7] show at C:\Users\ky642d\.julia\packages\QueryOperators\VfF5B\src\enumerable\show.jl:35 [inlined]
 [8] show(::IOContext{REPL.Terminals.TTYTerminal}, ::MIME{Symbol("text/plain")}, ::QueryOperators.EnumerableMap{NamedTuple{(:a, :b),Tuple{String,Int64}},QueryOperators.EnumerableIterable{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},Tables.DataValueRowIterator{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},Array{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},1}}},getfield(Main, Symbol("##8#10"))}) at .\sysimg.jl:195
 [9] display(::REPL.REPLDisplay, ::MIME{Symbol("text/plain")}, ::Any) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:131
 [10] display(::REPL.REPLDisplay, ::Any) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:135
 [11] display(::QueryOperators.EnumerableMap{NamedTuple{(:a, :b),Tuple{String,Int64}},QueryOperators.EnumerableIterable{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},Tables.DataValueRowIterator{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},Array{NamedTuple{(:a, :b),Tuple{DataValue{String},DataValue{Int64}}},1}}},getfield(Main, Symbol("##8#10"))}) at .\multimedia.jl:287
 [12] #invokelatest#1 at .\essentials.jl:691 [inlined]
 [13] invokelatest at .\essentials.jl:690 [inlined]
 [14] print_response(::IO, ::Any, ::Any, ::Bool, ::Bool, ::Any) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:154
 [15] print_response(::REPL.AbstractREPL, ::Any, ::Any, ::Bool, ::Bool) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:139
 [16] (::getfield(REPL, Symbol("#do_respond#40")){Bool,getfield(REPL, Symbol("##50#59")){REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:708
 [17] #invokelatest#1 at .\essentials.jl:691 [inlined]
 [18] invokelatest at .\essentials.jl:690 [inlined]
 [19] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\LineEdit.jl:2261
 [20] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:1029
 [21] run_repl(::REPL.AbstractREPL, ::Any) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:191
 [22] (::getfield(Base, Symbol("##831#833")){Bool,Bool,Bool,Bool})(::Module) at .\logging.jl:311
 [23] #invokelatest#1 at .\essentials.jl:691 [inlined]
 [24] invokelatest at .\essentials.jl:690 [inlined]
 [25] macro expansion at .\logging.jl:308 [inlined]
 [26] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at .\client.jl:340
 [27] exec_options(::Base.JLOptions) at .\client.jl:252
 [28] _start() at .\client.jl:432
```

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

File: src/datavalues.jl [hunk 1]
```diff
@@ -6,6 +6,9 @@ unwrap(x::DataValue) = isna(x) ? missing : DataValues.unsafe_get(x)
 datavaluetype(::Type{T}) where {T <: DataValue} = T
 datavaluetype(::Type{Union{T, Missing}}) where {T} = DataValue{T}
 datavaluetype(::Type{Missing}) = DataValue{Union{}}
+scalarconvert(T, x) = convert(T, x)
```
Comment (nalimilan) [inline src/datavalues.jl:9]: Would be nice to add a comment pointing to the issue, since we should be able to get rid of this at some point.
