### PR TITLE
Shim IteratorSize for DataValueRowIterator

### LINKED ISSUE #43: DataValueRowIterator incorrectly implements the IteratorSize trait
If the source of a ``DataValueRowIterator `` returns ``HasShape()`` for ``IteratorSize(x)``, then currently ``DataValueRowIterator`` just passes that value through, but then does not implement ``size``.

I think the solution would be to either properly implement ``size``, or to not just pass the value of ``IteratorSize(x)`` through, but e.g. return ``HasLength()`` if the source implements a size with 1 dimension or something like that.

This showed up as a bit in https://github.com/fredo-dedup/VegaLite.jl/issues/129.

### PR DESCRIPTION
**Pull request by davidanthoff**
Fixes #43, I think...

### CODE REVIEW

**Review by quinnj — APPROVED** [review]
Seems like a fine solution to me. Thanks!

File: src/datavalues.jl [hunk 1]
```diff
@@ -29,8 +29,11 @@ function datavaluerows(x)
     return DataValueRowIterator(datavaluetype(Tables.schema(r)), r)
 end
 
+_iteratorsize(x) = x
+_iteratorsize(::Base.HasShape{1}) = Base.HasLength()
```
Comment (nalimilan) [inline src/datavalues.jl:33]: I don't get the reasoning here. Why should we treat `HasShape{2}` differently from `HasShape{1}`?

Comment (davidanthoff) [reply src/datavalues.jl:33]: I don’t believe this will ever kick in for anything other then ``Vector``. I’m not sure, though, this is all getting very complex...

**Comment by davidanthoff** [comment]
@quinnj Could you also tag a new release?
